### ISSUE TITLE
Leave command exception

### ISSUE THREAD

**Issue by Floydan** [Floydan/discord-pickup-bot#1]
[04/09/2020 20:06:10 > a59750: INFO] 20:06:10 Command     Discord.Commands.CommandException: Error occurred executing "leave" for Floydan#0912 in Rocket Arena 3/pickup.
[04/09/2020 20:06:10 > a59750: INFO]  ---> System.InvalidCastException: Unable to cast object of type 'Discord.WebSocket.SocketGlobalUser' to type 'Discord.IGuildUser'.
[04/09/2020 20:06:10 > a59750: INFO]    at PickupBot.Commands.Modules.PickupModule.GetMention(IUser user) in C:\Projects\Private\Floydan\PickupBot\PickupBot.Commands\Modules\PickupModule.cs:line 318
[04/09/2020 20:06:10 > a59750: INFO]    at PickupBot.Commands.Modules.PickupModule.LeaveInternal(PickupQueue queue, Boolean notify) in C:\Projects\Private\Floydan\PickupBot\PickupBot.Commands\Modules\PickupModule.cs:line 290
[04/09/2020 20:06:10 > a59750: INFO]    at PickupBot.Commands.Modules.PickupModule.Leave(String queueName) in C:\Projects\Private\Floydan\PickupBot\PickupBot.Commands\Modules\PickupModule.cs:line 175
[04/09/2020 20:06:10 > a59750: INFO]    at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
[04/09/2020 20:06:10 > a59750: INFO] --- End of stack trace from previous location where exception was thrown ---
[04/09/2020 20:06:10 > a59750: INFO]    at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
[04/09/2020 20:06:10 > a59750: INFO]    --- End of inner exception stack trace ---

**Comment by Floydan** [comment]
Fixed in latest release
